/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedCollectionsNameRouteImport } from './routes/_authed.collections.$name'
import { Route as AuthedCollectionsNameSlugRouteImport } from './routes/_authed.collections.$name.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCollectionsNameRoute = AuthedCollectionsNameRouteImport.update({
  id: '/collections/$name',
  path: '/collections/$name',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCollectionsNameSlugRoute =
  AuthedCollectionsNameSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthedCollectionsNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/collections/$name': typeof AuthedCollectionsNameRouteWithChildren
  '/collections/$name/$slug': typeof AuthedCollectionsNameSlugRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/collections/$name': typeof AuthedCollectionsNameRouteWithChildren
  '/collections/$name/$slug': typeof AuthedCollectionsNameSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/collections/$name': typeof AuthedCollectionsNameRouteWithChildren
  '/_authed/collections/$name/$slug': typeof AuthedCollectionsNameSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/collections/$name' | '/collections/$name/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/collections/$name' | '/collections/$name/$slug'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/collections/$name'
    | '/_authed/collections/$name/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collections/$name': {
      id: '/_authed/collections/$name'
      path: '/collections/$name'
      fullPath: '/collections/$name'
      preLoaderRoute: typeof AuthedCollectionsNameRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collections/$name/$slug': {
      id: '/_authed/collections/$name/$slug'
      path: '/$slug'
      fullPath: '/collections/$name/$slug'
      preLoaderRoute: typeof AuthedCollectionsNameSlugRouteImport
      parentRoute: typeof AuthedCollectionsNameRoute
    }
  }
}

interface AuthedCollectionsNameRouteChildren {
  AuthedCollectionsNameSlugRoute: typeof AuthedCollectionsNameSlugRoute
}

const AuthedCollectionsNameRouteChildren: AuthedCollectionsNameRouteChildren = {
  AuthedCollectionsNameSlugRoute: AuthedCollectionsNameSlugRoute,
}

const AuthedCollectionsNameRouteWithChildren =
  AuthedCollectionsNameRoute._addFileChildren(
    AuthedCollectionsNameRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCollectionsNameRoute: typeof AuthedCollectionsNameRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCollectionsNameRoute: AuthedCollectionsNameRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
